Feat : 로그1차구현(차선책) (#101)
Knock-Og/BE pull request #103
Opened 2023-03-23 21:03 UTC by sunyeon-Jeong

### PR 타입
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링

### 반영 브랜치
feat/101/log_1 -> dev

### 변경 사항
- Post update 시, 로그생성
  - 말랑이님이 해당 페이지를 편집했습니다.
  - 편집한 시간 : 2023-03-20

### 테스트 결과
- Postman 테스트 결과 이상 없습니다.

2023-03-23 21:05 UTC, jyparkDev approved these changes
잘하셨어요~

2023-03-23 21:05 UTC, jyparkDev commented on src/main/java/com/project/comgle/entity/Log.java
> +    public static Log of(Post post, String content, String memberName) {
👍🏽

2023-03-23 21:05 UTC, jyparkDev commented on src/main/java/com/project/comgle/service/PostService.java
> +        Log newLog = Log.of(findPost.get(), content, member.getMemberName());
👍🏽

2023-03-23 22:41 UTC, jyparkDev approved these changes

2023-03-24 00:51 UTC, hunny-A approved these changes

2023-03-24 00:51 UTC, hunny-A commented on src/main/java/com/project/comgle/service/PostService.java
>          return ResponseEntity.ok().body(MessageResponseDto.of(HttpStatus.OK.value(), "수정 완료"));
로그 api가 따로 필요하지 않나요??

2023-03-24 03:31 UTC, jyparkDev commented on src/main/java/com/project/comgle/service/PostService.java
>          return ResponseEntity.ok().body(MessageResponseDto.of(HttpStatus.OK.value(), "수정 완료"));
> 로그 api가 따로 필요하지 않나요??

로그는 현재 게시글이 수정되는 api가 호출 되면서 수정 완료 시 별로도 만들어주면 되서 현재는 API는 필요없을 듯 합니다. 추후 상세 페이지에서 해당 게시글 관련 로그들을 모두 조회할 경우에 조회 API가 필요할 것 같다고 예상합니다 bb

2023-03-24 06:05 UTC, YeowonKIM requested changes

2023-03-24 06:05 UTC, YeowonKIM commented on src/main/java/com/project/comgle/entity/Log.java
> -        this.action = action;
action은 모호해서 빼셨네요 좋습니다 :)

2023-03-24 06:05 UTC, YeowonKIM commented on src/main/java/com/project/comgle/service/PostService.java
>          return ResponseEntity.ok().body(MessageResponseDto.of(HttpStatus.OK.value(), "수정 완료"));
로그가 상세페이지 조회할 때마다 필요한 게 아니라 
와이어프레임에 댓글처럼 누를 때마 조회하기 때문에 저도 따로 API가 필요하다고 생각했는데
프론트랑 한 번 이야기 해 보면 좋을 것 같습니다 :)

2023-03-24 08:14 UTC, merged