Feat : 편집 상태 구현 (SSE)
Knock-Og/BE pull request #111
Opened 2023-03-25 19:42 UTC by YeowonKIM

### PR 타입
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링

### 반영 브랜치
feat/67/editing-status-> develop

### 변경 사항
- 여러 멤버(sseEmitter)가 한 게시글에 대해 편집 상태 변경 -> 여러 게시글에 sse 동시에 돌아가도록 구현
- Post에 편집 상태 나타내는 editingStatus 칼럼 추가

### 테스트 결과
Postman 테스트 결과 이상 없습니다.

2023-03-26 03:44 UTC, jyparkDev requested changes
Post Entity 부분에 작성한 코드리뷰 확인 후 
변경사항이 없다면 의논하여 merge 시키는 방향이 좋을 것 같습니다.

2023-03-26 03:44 UTC, jyparkDev commented on src/main/java/com/project/comgle/dto/common/SchemaDescriptionUtils.java
> +        public static final String EditingStatus = "편집상태";
👍🏽

2023-03-26 03:44 UTC, jyparkDev commented on src/main/java/com/project/comgle/dto/request/PostRequestDto.java
> +    @Schema(description = SchemaDescriptionUtils.Post.EditingStatus,  example = "편집상태")
꼼꼼하게 적용 잘 해주셨네요 ^^

2023-03-26 03:44 UTC, jyparkDev commented on src/main/java/com/project/comgle/entity/Post.java
> +    private String editingStatus = "false";
현재 editingStatus 관련 초기화에 대해서 한번 정리 시켜줄 필요가 있다고 생각이듭니다.
명시적으로 초기화도 되어 있고 정적 팩토리 메서드에서도 초기화 시키고 있어보입니다.

2023-03-26 03:44 UTC, jyparkDev commented on src/main/java/com/project/comgle/service/PostService.java
> +        findSubscrbingPosts.getSseEmitters().forEach((postId, emitter) -> {
👍🏽

2023-03-26 03:44 UTC, jyparkDev commented on src/main/java/com/project/comgle/service/SseService.java
> +        SseEmitters postEmitters = emitterRepository.subscibePosts(postId);
👍🏽

2023-03-27 00:58 UTC, hunny-A approved these changes

2023-03-27 00:58 UTC, hunny-A commented on src/main/java/com/project/comgle/entity/SseEmitters.java
> +@Slf4j
본문 내에서 log를 사용하지 않는 것 같은데 sseEmitter을 사용할 때 필요한 건가요??

2023-03-27 01:21 UTC, sunyeon-Jeong approved these changes
굉장히 난이도가 높아보입니다!!! 고생 많으셨어요 멋져용 :)

2023-03-29 00:49 UTC, merged