Feat : Searched Page 카테고리 검색 조회 #82
Knock-Og/BE pull request #91
Opened 2023-03-20 10:16 UTC by YeowonKIM

### PR 타입
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링

### 반영 브랜치
feat/82/search-category-> develop

### 변경 사항
- Searched Page 카테고리 검색 기능 추가
- PostController url API 명세서 변경대로 수정
- CommentRepository에서 merge 하며 잘못 반영된 부분 복귀

### 테스트 결과
Postman 테스트 결과 이상 없습니다.

2023-03-20 11:43 UTC, hunny-A approved these changes

2023-03-20 11:43 UTC, hunny-A commented on src/main/java/com/project/comgle/controller/PostController.java
>      public ResponseEntity<PostResponseDto> readPost(@PathVariable("post-id") Long id, @AuthenticationPrincipal UserDetailsImpl userDetails) {
api 변경 확인했습니다 수고 많으셨습니다~!

2023-03-20 13:59 UTC, jyparkDev requested changes
고민해 볼 필요가 있는 내용이 있어 잠시 보류 시켰습니다^^

2023-03-20 13:59 UTC, jyparkDev commented on src/main/java/com/project/comgle/repository/CommentRepository.java
> +    List<Comment> findAllByPostOrderByCreatedAtDesc(Post post);
생성일 기준 내림차순 조회 선택하셨네요
확인했습니다 👍🏽

2023-03-21 09:11 UTC, hunny-A approved these changes

2023-03-21 09:11 UTC, hunny-A commented on src/main/java/com/project/comgle/service/SearchService.java
> +        Optional<Category> findCategory = categoryRepository.findByCategoryNameAndCompany(category, member.getCompany());
변경사항 확인 했습니다 bbbb

2023-03-21 09:39 UTC, jyparkDev approved these changes
잘하셨네요 👍🏽

2023-03-21 09:41 UTC, merged